### ISSUE TITLE
mistake in logger

### ISSUE THREAD

**Issue by gervasiozaldivar** [franklhy/silc#12]
In silc/md/logger.py

        if self.counter > self.offset and self.counter % self.period_hist_force == 0:
            hist = state.hist
            if self.hist is None:
                self.hist = copy.copy(hist)
                self.hist_cum = copy.copy(hist)
            else:
                self.hist = hist - self.hist_cum
                **self.dhist_cum = copy.copy(hist)**
            self.save_file_hist()

seld.dhist_cum should be self.hist.cum, right?

**Comment by franklhy** [comment]
You are right. I created a PR that fixes the typo.
