### ISSUE TITLE
Issue with tutorial.py and tutorial_asym.py

### ISSUE THREAD

**Issue by gustavor101** [franklhy/silc#4]
Trying to run the tutorial examples both fail with error:
File "tutorial_asym.py", line 43, in <module>
    c.create_receptor_motif_complex(n_motif=2, dock_pose_id=0)
  File "/storage3/silc-env/lib/python3.8/site-packages/silc/build_molecule.py", line 413, in create_receptor_motif_complex
    self.dock.receptor, motifs = util.optimize_complex(self.dock.receptor, motifs, expanded_cores)
  File "/storage3/silc-env/lib/python3.8/site-packages/silc/util.py", line 192, in optimize_complex
    complex = AllChem.CombineMols(mols[0], mols[1])
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdmolops.CombineMols(NoneType, Mol)
did not match C++ signature:
    CombineMols(RDKit::ROMol mol1, RDKit::ROMol mol2, RDGeom::Point3D offset=<rdkit.Geometry.rdGeometry.Point3D object at 0x7f75ebc696c0>)
File "tutorial.py", line 43, in <module>
    c.create_receptor_motif_complex(n_motif=2, dock_pose_id=19, solvate=True)    # X-shape, "trans"
  File "/storage3/silc-env/lib/python3.8/site-packages/silc/build_molecule.py", line 413, in create_receptor_motif_complex
    self.dock.receptor, motifs = util.optimize_complex(self.dock.receptor, motifs, expanded_cores)
  File "/storage3/silc-env/lib/python3.8/site-packages/silc/util.py", line 192, in optimize_complex
    complex = AllChem.CombineMols(mols[0], mols[1])
Boost.Python.ArgumentError: Python argument types in
    rdkit.Chem.rdmolops.CombineMols(NoneType, Mol)
did not match C++ signature:
    CombineMols(RDKit::ROMol mol1, RDKit::ROMol mol2, RDGeom::Point3D offset=<rdkit.Geometry.rdGeometry.Point3D object at 0x7f15fe62d640>)

**Comment by franklhy** [comment]
I cannot reproduce this error. It seems that it fails to load the docking configuration from `silc/data/tutorial/docking/symmetric_core` and `silc/data/tutorial/docking/asymmetric_core`. Did you modify the tutorial.py and tutorial_asym.py code?

**Comment by gustavor101** [comment]
No, they are the same files than in the biased_md branch. Here is my conda list:
# packages in environment at /storage3/silc-env:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
ambertools                23.3             py38hce2aceb_6    conda-forge
amberutils                21.0                     pypi_0    pypi
anyio                     4.2.0                    pypi_0    pypi
argon2-cffi               23.1.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
arpack                    3.8.0           nompi_h0baa96a_101    conda-forge
arrow                     1.3.0                    pypi_0    pypi
asttokens                 2.4.1                    pypi_0    pypi
async-lru                 2.0.4                    pypi_0    pypi
attrs                     23.2.0                   pypi_0    pypi
babel                     2.14.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.12.3                   pypi_0    pypi
bleach                    6.1.0                    pypi_0    pypi
blosc                     1.21.5               h0f2a231_0    conda-forge
boost                     1.82.0               hb563948_6    conda-forge
boost-cpp                 1.82.0               h44aadfe_6    conda-forge
brotli                    1.1.0                hd590300_1    conda-forge
brotli-bin                1.1.0                hd590300_1    conda-forge
brotli-python             1.1.0            py38h17151c0_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.25.0               hd590300_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
cffi                      1.16.0                   pypi_0    pypi
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
comm                      0.2.1                    pypi_0    pypi
contourpy                 1.1.1            py38h7f3f72f_1    conda-forge
cudatoolkit               11.5.2              hbdc67f6_12    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
debugpy                   1.8.0                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.7                    pypi_0    pypi
edgembar                  0.2                      pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
executing                 2.0.1                    pypi_0    pypi
fastjsonschema            2.19.1                   pypi_0    pypi
fftw                      3.3.10          nompi_hc118613_108    conda-forge
fonttools                 4.47.2           py38h01eb140_0    conda-forge
fqdn                      1.5.1                    pypi_0    pypi
freetype                  2.12.1               h267a509_2    conda-forge
hdf4                      4.2.15               h2a13503_7    conda-forge
hdf5                      1.14.3          nompi_h4f84152_100    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
importlib-metadata        7.0.1                    pypi_0    pypi
importlib-resources       6.1.1              pyhd8ed1ab_0    conda-forge
importlib_resources       6.1.1              pyhd8ed1ab_0    conda-forge
ipykernel                 6.29.0                   pypi_0    pypi
ipython                   8.12.3                   pypi_0    pypi
isoduration               20.11.0                  pypi_0    pypi
jedi                      0.19.1                   pypi_0    pypi
jinja2                    3.1.3                    pypi_0    pypi
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
json5                     0.9.14                   pypi_0    pypi
jsonpointer               2.4                      pypi_0    pypi
jsonschema                4.21.0                   pypi_0    pypi
jsonschema-specifications 2023.12.1                pypi_0    pypi
jupyter-client            8.6.0                    pypi_0    pypi
jupyter-core              5.7.1                    pypi_0    pypi
jupyter-events            0.9.0                    pypi_0    pypi
jupyter-lsp               2.2.2                    pypi_0    pypi
jupyter-server            2.12.5                   pypi_0    pypi
jupyter-server-terminals  0.5.1                    pypi_0    pypi
jupyterlab                4.0.10                   pypi_0    pypi
jupyterlab-pygments       0.3.0                    pypi_0    pypi
jupyterlab-server         2.25.2                   pypi_0    pypi
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.5            py38h7f3f72f_1    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.1.2                h59595ed_1    conda-forge
libblas                   3.9.0           20_linux64_openblas    conda-forge
libboost                  1.82.0               h6fcfa73_6    conda-forge
libboost-devel            1.82.0               h00ab1b0_6    conda-forge
libboost-headers          1.82.0               ha770c72_6    conda-forge
libboost-python           1.82.0           py38hae673b5_6    conda-forge
libboost-python-devel     1.82.0           py38hb563948_6    conda-forge
libbrotlicommon           1.1.0                hd590300_1    conda-forge
libbrotlidec              1.1.0                hd590300_1    conda-forge
libbrotlienc              1.1.0                hd590300_1    conda-forge
libcblas                  3.9.0           20_linux64_openblas    conda-forge
libcurl                   8.5.0                hca28451_0    conda-forge
libdeflate                1.19                 hd590300_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgfortran-ng            13.2.0               h69a702a_3    conda-forge
libgfortran5              13.2.0               ha4646dd_3    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           20_linux64_openblas    conda-forge
libnetcdf                 4.9.2           nompi_h9612171_113    conda-forge
libnghttp2                1.58.0               h47da74e_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libtiff                   4.6.0                ha9c0a0a_2    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.2                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.4               h232c23b_1    conda-forge
libzip                    1.10.1               h2629f0a_3    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
markupsafe                2.1.3                    pypi_0    pypi
matplotlib-base           3.7.3            py38h58ed7fa_0    conda-forge
matplotlib-inline         0.1.6                    pypi_0    pypi
meeko                     0.5.0                    pypi_0    pypi
mistune                   3.0.2                    pypi_0    pypi
mmpbsa-py                 16.0                     pypi_0    pypi
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.9.0                    pypi_0    pypi
nbconvert                 7.14.2                   pypi_0    pypi
nbformat                  5.9.2                    pypi_0    pypi
ncurses                   6.4                  h59595ed_2    conda-forge
nest-asyncio              1.5.9                    pypi_0    pypi
netcdf-fortran            4.6.1           nompi_hacb5139_103    conda-forge
notebook-shim             0.2.3                    pypi_0    pypi
numpy                     1.24.4           py38h59b608b_0    conda-forge
ocl-icd                   2.3.1                h7f98852_0    conda-forge
ocl-icd-system            1.0.0                         1    conda-forge
openjpeg                  2.5.0                h488ebb8_3    conda-forge
openmm                    8.1.1            py38h172b3f9_0    conda-forge
openssl                   3.2.0                hd590300_1    conda-forge
overrides                 7.4.0                    pypi_0    pypi
packaging                 23.2               pyhd8ed1ab_0    conda-forge
packmol                   20.010               h86c2bf4_0    conda-forge
packmol-memgen            2023.2.24                pypi_0    pypi
pandas                    2.0.3            py38h01efb38_1    conda-forge
pandocfilters             1.5.0                    pypi_0    pypi
parmed                    4.2.2            py38h17151c0_1    conda-forge
parso                     0.8.3                    pypi_0    pypi
pdb4amber                 22.0                     pypi_0    pypi
perl                      5.32.1          7_hd590300_perl5    conda-forge
pexpect                   4.9.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    10.2.0           py38ha43c96d_0    conda-forge
pip                       23.3.2             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              4.1.0              pyhd8ed1ab_0    conda-forge
pooch                     1.8.0              pyhd8ed1ab_0    conda-forge
prometheus-client         0.19.0                   pypi_0    pypi
prompt-toolkit            3.0.43                   pypi_0    pypi
psutil                    5.9.7                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
py3dmol                   2.0.4                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pygments                  2.17.2                   pypi_0    pypi
pymsmt                    22.0                     pypi_0    pypi
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.8.18          hd12c33a_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7                    pypi_0    pypi
python-tzdata             2023.4             pyhd8ed1ab_0    conda-forge
python_abi                3.8                      4_cp38    conda-forge
pytraj                    2.0.6                    pypi_0    pypi
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1                    pypi_0    pypi
pyzmq                     25.1.2                   pypi_0    pypi
rdkit                     2023.9.4                 pypi_0    pypi
readline                  8.2                  h8228510_1    conda-forge
referencing               0.32.1                   pypi_0    pypi
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rfc3339-validator         0.1.4                    pypi_0    pypi
rfc3986-validator         0.1.1                    pypi_0    pypi
rpds-py                   0.17.1                   pypi_0    pypi
sander                    22.0                     pypi_0    pypi
scipy                     1.10.1           py38h59b608b_3    conda-forge
send2trash                1.8.2                    pypi_0    pypi
setuptools                69.0.3             pyhd8ed1ab_0    conda-forge
silc                      0.1.0                    pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h9fff704_0    conda-forge
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.5                      pypi_0    pypi
stack-data                0.6.3                    pypi_0    pypi
terminado                 0.18.0                   pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.0.1                    pypi_0    pypi
tornado                   6.4                      pypi_0    pypi
traitlets                 5.14.1                   pypi_0    pypi
types-python-dateutil     2.8.19.20240106          pypi_0    pypi
typing-extensions         4.9.0                    pypi_0    pypi
unicodedata2              15.1.0           py38h01eb140_0    conda-forge
uri-template              1.3.0                    pypi_0    pypi
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
vina                      1.2.5                    pypi_0    pypi
wcwidth                   0.2.13                   pypi_0    pypi
webcolors                 1.13                     pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.7.0                    pypi_0    pypi
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.7                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxt                1.3.0                hd590300_1    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge

**Comment by gustavor101** [comment]
Using rdkit 2023.9.1 instead of rdkit 2023.9.4 solves the issue.

**Comment by franklhy** [comment]
@gustavor101 I created a new branch named `read_receptor` which uses MDAnalysis to read the topology and pdb of receptors. Could you please try it with both rdkit 2023.9.1 and rdkit 2023.9.4?

**Comment by gustavor101** [comment]
Both examples work with either rdkit 2023.9.1 or 2023.9.4 in combination with mdanalysis 2.4.3.
